--1.
SELECT NAZWISKO, (SUBSTR(ETAT,1,2) || ID_PRAC) AS KOD FROM PRACOWNICY;

--2.
SELECT NAZWISKO, (REPLACE(REPLACE(REPLACE(NAZWISKO, 'K', 'X'), 'L', 'X'), 'M', 'X')) AS WOJNA_LITEROM FROM PRACOWNICY;

--3.
SELECT NAZWISKO FROM PRACOWNICY WHERE INSTR(NAZWISKO, 'L',1,1)<=LENGTH(NAZWISKO)/2 AND INSTR(NAZWISKO, 'L',1,1)!=0;

--4.
SELECT NAZWISKO, ROUND(PLACA_POD*1.15) AS PODWYZKA FROM PRACOWNICY;

--5.
SELECT NAZWISKO, PLACA_POD, (PLACA_POD*0.2) AS INWESTYCJA, ((PLACA_POD*0.2)*POWER(1.1,10)) AS KAPITAL, (((PLACA_POD*0.2)*POWER(1.1,10))-(PLACA_POD*0.2)) AS ZYSK FROM PRACOWNICY;

--6.
SELECT NAZWISKO, ZATRUDNIONY, TRUNC(MONTHS_BETWEEN(DATE '2000-01-01',ZATRUDNIONY)/12) AS STAZ_W_2000 FROM PRACOWNICY;

--7.
SELECT NAZWISKO, (TO_CHAR(ZATRUDNIONY, 'fmMONTH, DD, YYYY')) AS DATA_ZATRUDNIENIA FROM PRACOWNICY WHERE ID_ZESP = 20;

--8.
SELECT UNIQUE (TO_CHAR(CURRENT_DATE, 'fmDAY')) AS DZIS FROM PRACOWNICY;

--9.
SELECT NAZWA, ADRES, CASE ADRES WHEN 'PIOTROWO 3A' THEN 'NOWE MIASTO' WHEN 'STRZELECKA 14' THEN 'STARE MIASTO' WHEN 'WLODKOWICA 16' THEN 'GRUNWALD' WHEN 'MIELZYNSKIEGO 30' THEN 'STARE MIASTO' END AS DZIELNICA FROM ZESPOLY;

--10.
SELECT NAZWISKO, PLACA_POD, CASE SIGN(PLACA_POD-480) WHEN -1 THEN 'Poniżej 400' WHEN 0 THEN 'Dokładnie 400' WHEN 1 THEN 'Powyżej 400' END AS PROG FROM PRACOWNICY ORDER BY PLACA_POD DESC;

--11.
SELECT NAZWISKO, PLACA_POD, DECODE(SIGN(PLACA_POD-480),-1,'Poniżej 400',0,'Dokładnie 400',1,'Powyżej 400') AS PROG FROM PRACOWNICY ORDER BY PLACA_POD DESC;