INSERT INTO pracownicy(id_prac, nazwisko) VALUES ((SELECT max(id_prac) + 1 FROM pracownicy), 'WOLNY');

--1.
SELECT P.NAZWISKO, P.ID_ZESP, Z.NAZWA FROM PRACOWNICY P LEFT OUTER JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY NAZWISKO;

--2.
SELECT Z.NAZWA, Z.ID_ZESP, CASE WHEN P.NAZWISKO IS NOT NULL THEN P.NAZWISKO ELSE 'brak pracowników' END AS PRACOWNIK FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY Z.NAZWA, P.NAZWISKO;

--3.
SELECT CASE WHEN Z.NAZWA IS NOT NULL THEN Z.NAZWA ELSE 'brak zespołu' END AS ZESPOL, CASE WHEN P.NAZWISKO IS NOT NULL THEN P.NAZWISKO ELSE 'brak pracowników' END AS PRACOWNIK FROM PRACOWNICY P FULL OUTER JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY Z.NAZWA, P.NAZWISKO;

DELETE FROM PRACOWNICY WHERE NAZWISKO = 'WOLNY';

--4.
SELECT Z.NAZWA AS ZESPOL, COUNT(P.ID_PRAC) AS LICZBA, SUM(COALESCE(P.PLACA_POD,0)) AS SUMA_PLAC FROM ZESPOLY Z LEFT OUTER JOIN PRACOWNICY P ON P.ID_ZESP=Z.ID_ZESP GROUP BY Z.ID_ZESP ORDER BY Z.NAZWA;

--5.
SELECT Z.NAZWA FROM ZESPOLY Z LEFT OUTER JOIN PRACOWNICY P ON P.ID_ZESP=Z.ID_ZESP GROUP BY Z.ID_ZESP ORDER BY Z.NAZWA;

--6.
SELECT P1.NAZWISKO, P1.ID_PRAC, P2.NAZWISKO AS SZEF, P1.ID_SZEFA FROM PRACOWNICY P1 LEFT OUTER JOIN PRACOWNICY P2 ON P1.ID_SZEFA=P2.ID_PRAC ORDER BY P1.NAZWISKO;

--7.
SELECT P1.NAZWISKO, COUNT(P2.ID_PRAC) AS LICZBA_PODWLADNYCH FROM PRACOWNICY P1 LEFT OUTER JOIN PRACOWNICY P2 ON P1.ID_PRAC=P2.ID_SZEFA GROUP BY P1.NAZWISKO ORDER BY P1.NAZWISKO;

--8.
SELECT P1.NAZWISKO, P1.ETAT, P1.PLACA_POD, Z1.NAZWA, P2.NAZWISKO AS SZEF FROM PRACOWNICY P1 LEFT OUTER JOIN PRACOWNICY P2 ON P1.ID_SZEFA = P2.ID_PRAC INNER JOIN ZESPOLY Z1 ON P1.ID_ZESP = Z1.ID_ZESP ORDER BY P1.NAZWISKO;

--9.
SELECT P1.NAZWISKO, Z1.NAZWA FROM PRACOWNICY P1 CROSS JOIN ZESPOLY Z1 ORDER BY P1.NAZWISKO, Z1.NAZWA;

--10.
SELECT COUNT(*) FROM ETATY CROSS JOIN PRACOWNICY CROSS JOIN ZESPOLY;

--11.
SELECT ETAT FROM PRACOWNICY WHERE ZATRUDNIONY >= '1992-01-01' AND ZATRUDNIONY < '1993-01-01' UNION SELECT ETAT FROM PRACOWNICY WHERE ZATRUDNIONY >= '1993-01-01' AND ZATRUDNIONY < '1994-01-01' ORDER BY ETAT;

--12.
SELECT Z1.ID_ZESP FROM ZESPOLY Z1 LEFT OUTER JOIN PRACOWNICY P1 ON Z1.ID_ZESP = P1.ID_ZESP GROUP BY Z1.ID_ZESP HAVING COUNT(P1.ID_PRAC) = 0;

--13.
SELECT MEDIAN(Z1.ID_ZESP) AS ID_ZESP, Z1.NAZWA AS NAZWA FROM ZESPOLY Z1 LEFT OUTER JOIN PRACOWNICY P1 ON Z1.ID_ZESP = P1.ID_ZESP GROUP BY Z1.NAZWA HAVING COUNT(P1.ID_PRAC) = 0;

--14.
SELECT NAZWISKO, PLACA_POD, 'Poniżej 480 złotych' AS PROG FROM PRACOWNICY WHERE PLACA_POD < 480
UNION
SELECT NAZWISKO, PLACA_POD, 'Dokładnie 480 złotych' AS PROG FROM PRACOWNICY WHERE PLACA_POD = 480
UNION
SELECT NAZWISKO, PLACA_POD, 'Powyżej 480 złotych' AS PROG FROM PRACOWNICY WHERE PLACA_POD > 480 ORDER BY PLACA_POD;