SELECT * FROM PRACOWNICY;

--1.
INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, ID_ZESP)
VALUES (250, 'KOWALSKI', 'ASYSTENT', TO_DATE('2015-01-13','YYYY-MM-DD'), 1500, 10);

INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, ID_ZESP)
VALUES (260, 'ADAMSKI', 'ASYSTENT', TO_DATE('2014-09-10','YYYY-MM-DD'), 1500, 10);

INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, PLACA_DOD, ID_ZESP)
VALUES (270, 'NOWAK', 'ADIUNKT', TO_DATE('1990-05-01','YYYY-MM-DD'), 2050, 540, 20);

SELECT * FROM PRACOWNICY WHERE ID_PRAC >= 250;

--2.
UPDATE PRACOWNICY
SET PLACA_POD = PLACA_POD*1.1, PLACA_DOD = COALESCE(PLACA_DOD, 100/1.2)*1.2
WHERE ID_PRAC >= 250;

SELECT * FROM PRACOWNICY WHERE ID_PRAC >= 250;

--3.
INSERT INTO ZESPOLY (ID_ZESP, NAZWA, ADRES)
VALUES (60, 'BAZY DANYCH', 'PIOTROWO 2');

SELECT * FROM ZESPOLY WHERE ID_ZESP = 60;

--4.
UPDATE PRACOWNICY
SET ID_ZESP =
(SELECT ID_ZESP FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH')
WHERE ID_PRAC >= 250;

SELECT * FROM PRACOWNICY
WHERE ID_ZESP =
(SELECT ID_ZESP FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH');

--5.
UPDATE PRACOWNICY
SET ID_SZEFA =
(SELECT ID_PRAC FROM PRACOWNICY
WHERE NAZWISKO LIKE 'MORZY')
WHERE ID_PRAC >= 250;

SELECT * FROM PRACOWNICY
WHERE ID_SZEFA =
(SELECT ID_PRAC FROM PRACOWNICY
WHERE NAZWISKO LIKE 'MORZY');

--6.
DELETE FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH';

--Nie można, ponieważ wskazują na niego inne rekordy podrzędne

--7.
DELETE FROM PRACOWNICY
WHERE ID_ZESP =
(SELECT ID_ZESP FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH');

DELETE FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH';

SELECT * FROM PRACOWNICY
WHERE ID_ZESP =
(SELECT ID_ZESP FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH');

SELECT * FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH';

--8.
SELECT NAZWISKO, PLACA_POD, (SELECT AVG(PLACA_POD) FROM PRACOWNICY GROUP BY ID_ZESP HAVING ID_ZESP = P.ID_ZESP)*0.1 AS PODWYZKA FROM PRACOWNICY P ORDER BY NAZWISKO;

--9.
UPDATE PRACOWNICY P
SET PLACA_POD = PLACA_POD + (SELECT AVG(PLACA_POD) FROM PRACOWNICY GROUP BY ID_ZESP HAVING ID_ZESP = P.ID_ZESP)*0.1;

SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY P ORDER BY NAZWISKO;

--10.
SELECT * FROM PRACOWNICY WHERE PLACA_POD = (SELECT MIN(PLACA_POD) FROM PRACOWNICY);

--11.
UPDATE PRACOWNICY P
SET PLACA_POD = ROUND((SELECT AVG(PLACA_POD) FROM PRACOWNICY), 2)
WHERE PLACA_POD = (SELECT MIN(PLACA_POD) FROM PRACOWNICY);

SELECT * FROM PRACOWNICY WHERE ID_PRAC = 200;

--12.
SELECT NAZWISKO, PLACA_DOD FROM PRACOWNICY WHERE ID_ZESP = 20 ORDER BY NAZWISKO;

UPDATE PRACOWNICY
SET PLACA_DOD = (SELECT AVG(P2.PLACA_POD) FROM PRACOWNICY P1 LEFT OUTER JOIN PRACOWNICY P2 ON P1.ID_PRAC = P2.ID_SZEFA GROUP BY P1.NAZWISKO HAVING P1.NAZWISKO LIKE 'MORZY')
WHERE ID_ZESP = 20;

SELECT NAZWISKO, PLACA_DOD FROM PRACOWNICY WHERE ID_ZESP = 20 ORDER BY NAZWISKO;

--13.
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA LIKE 'SYSTEMY ROZPROSZONE') ORDER BY NAZWISKO;

UPDATE PRACOWNICY
SET PLACA_POD = PLACA_POD * 1.25
WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA LIKE 'SYSTEMY ROZPROSZONE');

SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA LIKE 'SYSTEMY ROZPROSZONE') ORDER BY NAZWISKO;

--14.
SELECT P2.NAZWISKO FROM PRACOWNICY P1 LEFT OUTER JOIN PRACOWNICY P2 ON P1.ID_PRAC = P2.ID_SZEFA WHERE P1.NAZWISKO LIKE 'MORZY';

DELETE FROM PRACOWNICY
WHERE ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO LIKE 'MORZY');

SELECT P2.NAZWISKO FROM PRACOWNICY P1 LEFT OUTER JOIN PRACOWNICY P2 ON P1.ID_PRAC = P2.ID_SZEFA WHERE P1.NAZWISKO LIKE 'MORZY';

--15.
SELECT * FROM PRACOWNICY;

--16.
CREATE SEQUENCE ID_PRAC_SEQ START WITH 300 INCREMENT BY 10;

--17.
INSERT INTO PRACOWNICY P1 (ID_PRAC, NAZWISKO, ETAT, PLACA_POD)
VALUES(ID_PRAC_SEQ.NEXTVAL, 'Trąbczyński', 'STAZYSTA', 1000);

--18.
UPDATE PRACOWNICY
SET PLACA_DOD = ID_PRAC_SEQ.CURRVAL
WHERE ID_PRAC = 300;

--19.
DELETE FROM PRACOWNICY
WHERE NAZWISKO LIKE 'Trąbczyński';

--20.
CREATE SEQUENCE LOW_SEQ START WITH 10 INCREMENT BY 10 MAXVALUE 20;

--21.
DROP SEQUENCE LOW_SEQ;