INSERT INTO pracownicy(id_prac, nazwisko) VALUES ((SELECT max(id_prac) + 1 FROM pracownicy), 'WOLNY');

--1.
SELECT P.NAZWISKO, P.ID_ZESP, Z.NAZWA FROM PRACOWNICY P LEFT OUTER JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY NAZWISKO;

--2.
SELECT Z.NAZWA, Z.ID_ZESP, CASE WHEN P.NAZWISKO IS NOT NULL THEN P.NAZWISKO ELSE 'brak pracowników' END AS PRACOWNIK FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY Z.NAZWA, P.NAZWISKO;

--3.
SELECT CASE WHEN Z.NAZWA IS NOT NULL THEN Z.NAZWA ELSE 'brak zespołu' END AS ZESPOL, CASE WHEN P.NAZWISKO IS NOT NULL THEN P.NAZWISKO ELSE 'brak pracowników' END AS PRACOWNIK FROM PRACOWNICY P FULL OUTER JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY Z.NAZWA, P.NAZWISKO;

DELETE FROM PRACOWNICY WHERE NAZWISKO = 'WOLNY';

--4.
SELECT Z.NAZWA AS ZESPOL, COUNT(P.ID_PRAC) AS LICZBA, SUM(COALESCE(P.PLACA_POD,0)) AS SUMA_PLAC FROM ZESPOLY Z LEFT OUTER JOIN PRACOWNICY P ON P.ID_ZESP=Z.ID_ZESP GROUP BY Z.ID_ZESP ORDER BY Z.NAZWA;

--5.
SELECT Z.NAZWA FROM ZESPOLY Z LEFT OUTER JOIN PRACOWNICY P ON P.ID_ZESP=Z.ID_ZESP GROUP BY Z.ID_ZESP ORDER BY Z.NAZWA;

--6.
SELECT P1.NAZWISKO, P1.ID_PRAC, P2.NAZWISKO AS SZEF, P1.ID_SZEFA FROM PRACOWNICY P1 LEFT OUTER JOIN PRACOWNICY P2 ON P1.ID_SZEFA=P2.ID_PRAC ORDER BY P1.NAZWISKO;

--7.
SELECT P1.NAZWISKO, P1.ID_PRAC, P2.NAZWISKO AS SZEF, P1.ID_SZEFA FROM PRACOWNICY P1 LEFT OUTER JOIN PRACOWNICY P2 ON P1.ID_SZEFA=P2.ID_PRAC ORDER BY P1.NAZWISKO;

--8.

--9.

--10.

--11.

--12.

--13.

--14.