--1.
SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY WHERE ID_ZESP = (SELECT ID_ZESP FROM PRACOWNICY WHERE NAZWISKO LIKE 'BRZEZINSKI') ORDER BY NAZWISKO;

--2.
SELECT P.NAZWISKO, P.ETAT, Z.NAZWA FROM PRACOWNICY P JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP WHERE P.ID_ZESP = (SELECT ID_ZESP FROM PRACOWNICY WHERE NAZWISKO LIKE 'BRZEZINSKI') ORDER BY NAZWISKO;

INSERT INTO pracownicy(id_prac, nazwisko, etat, zatrudniony) 
VALUES ((SELECT max(id_prac) + 1 FROM pracownicy), 
 'WOLNY', 'ASYSTENT', DATE '1968-07-01');

--3.
SELECT NAZWISKO, ETAT, ZATRUDNIONY FROM PRACOWNICY WHERE ETAT LIKE 'PROFESOR' AND MONTHS_BETWEEN(ZATRUDNIONY,CURRENT_DATE) <= (SELECT MIN(MONTHS_BETWEEN(ZATRUDNIONY,CURRENT_DATE)) FROM PRACOWNICY WHERE ETAT LIKE 'PROFESOR');

--4.
SELECT NAZWISKO, ZATRUDNIONY, ID_ZESP FROM PRACOWNICY WHERE ID_ZESP IS NOT NULL AND (ID_ZESP, ZATRUDNIONY) IN (SELECT ID_ZESP, MAX(ZATRUDNIONY) FROM PRACOWNICY GROUP BY ID_ZESP);