SELECT * FROM PRACOWNICY;

--1.
INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, ID_ZESP)
VALUES (250, 'KOWALSKI', 'ASYSTENT', TO_DATE('2015-01-13','YYYY-MM-DD'), 1500, 10);

INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, ID_ZESP)
VALUES (260, 'ADAMSKI', 'ASYSTENT', TO_DATE('2014-09-10','YYYY-MM-DD'), 1500, 10);

INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, PLACA_DOD, ID_ZESP)
VALUES (270, 'NOWAK', 'ADIUNKT', TO_DATE('1990-05-01','YYYY-MM-DD'), 2050, 540, 20);

SELECT * FROM PRACOWNICY WHERE ID_PRAC >= 250;

--2.
UPDATE PRACOWNICY
SET PLACA_POD = PLACA_POD*1.1, PLACA_DOD = COALESCE(PLACA_DOD, 100/1.2)*1.2
WHERE ID_PRAC >= 250;

SELECT * FROM PRACOWNICY WHERE ID_PRAC >= 250;

--3.
INSERT INTO ZESPOLY (ID_ZESP, NAZWA, ADRES)
VALUES (60, 'BAZY DANYCH', 'PIOTROWO 2');

SELECT * FROM ZESPOLY WHERE ID_ZESP = 60;

--4.
UPDATE PRACOWNICY
SET ID_ZESP =
(SELECT ID_ZESP FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH')
WHERE ID_PRAC >= 250;

SELECT * FROM PRACOWNICY
WHERE ID_ZESP =
(SELECT ID_ZESP FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH');

--5.
UPDATE PRACOWNICY
SET ID_SZEFA =
(SELECT ID_PRAC FROM PRACOWNICY
WHERE NAZWISKO LIKE 'MORZY')
WHERE ID_PRAC >= 250;

SELECT * FROM PRACOWNICY
WHERE ID_SZEFA =
(SELECT ID_PRAC FROM PRACOWNICY
WHERE NAZWISKO LIKE 'MORZY');

--6.
DELETE FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH';

--Nie można, ponieważ wskazują na niego inne rekordy podrzędne

--7.
DELETE FROM PRACOWNICY
WHERE ID_ZESP =
(SELECT ID_ZESP FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH');

DELETE FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH';

SELECT * FROM PRACOWNICY
WHERE ID_ZESP =
(SELECT ID_ZESP FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH');

SELECT * FROM ZESPOLY
WHERE NAZWA LIKE 'BAZY DANYCH';

--8.
SELECT NAZWISKO, PLACA_POD, (SELECT AVG(PLACA_POD) FROM PRACOWNICY GROUP BY ID_ZESP)*0.1 FROM PRACOWNICY;